default_platform(:ios)

platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_P8_BASE64"],
      is_key_content_base64: true,
      in_house: false
    )

    match(
      type: "appstore",
      app_identifier: ENV["APPLE_BUNDLE_ID"],
      git_url: ENV["MATCH_GIT_URL"],
      api_key: api_key,
      force: true,
      force_for_new_certificates: true,
      readonly: false
    )

    sh("cd ../.. && flutter build ipa --release --export-options-plist=ios/ExportOptions.plist")

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end