platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_P8"]
    )
    cert(api_key: api_key, keychain_password: "")
    sigh(force: true, api_key: api_key)
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    sh("cd .. && flutter build ipa --release --export-method app-store --team K7R3D85XYA")
    pilot(api_key: api_key)
  end
end
