name: iOS Build
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.9"
      - run: flutter pub get
      - run: cd ios && pod install --repo-update
      - run: flutter build ipa --release --no-codesign
