name: iOS Build
on:
  workflow_dispatch:
    inputs:
      match_readonly:
        description: 'Readonly mode? Uncheck for first run'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.41.9'
      - run: flutter pub get
      - run: cd ios && pod install --repo-update
      - run: flutter build ios --release --no-codesign
